# Generated by Django 5.2.6 on 2025-09-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyposturescore',
            name='date',
            field=models.DateField(),
        ),
    ]
